

services:
  etl:
    build: .
    container_name: northwind-etl
    command: python runEtl.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs

  app:
    build: .
    container_name: northwind-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - etl
    restart: always




